### ISSUE TITLE
Ensure configuration files align with current standards in the main PatternFly repos / previous package within PF-React 

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/react-log-viewer#14]
- [x] Check that dependencies have proper semver characters resolved by #16
- [x] Check that installing dependencies does not cause any warnings resolved by #16 (other than warnings caused by other PF packages)
- [x] Check that dependencies are properly sorted into deps/devDeps/peerDeps resolved by #16
- [ ] #17
- [x] Check that linting does not cause any errors/warnings to be thrown
- [x] Check that tsconfig matches configuration as it existed in the pre-extraction package
- [x] Check that running a build does not cause any errors/warnings

**Comment by wise-king-sullyman** [comment]
All items other than #17 were resolved in #16. #17 is blocked by #18.
